// tools/templates/frontend/react/frontend/src/App.jsx
import { Routes, Route, Link } from 'react-router-dom';
import Home from './components/Home';
<% if (modules.contact) { -%>
import Contact from './components/Contact';
<% } -%>
<% if (modules.admin) { -%>
import Dashboard from './components/Dashboard';
<% } -%>

function App() {
  return (
    <div className="app">
      <nav>
        <Link to="/">Home</Link>
<% if (modules.contact) { -%>
        <Link to="/contact">Contact</Link>
<% } -%>
<% if (modules.auth) { -%>
        <Link to="/login">Login</Link>
<% } -%>
<% if (modules.admin) { -%>
        <Link to="/dashboard">Dashboard</Link>
<% } -%>
      </nav>

      <main>
        <Routes>
          <Route path="/" element={<Home />} />
<% if (modules.contact) { -%>
          <Route path="/contact" element={<Contact />} />
<% } -%>
<% if (modules.admin) { -%>
          <Route path="/dashboard" element={<Dashboard />} />
<% } -%>
        </Routes>
      </main>
    </div>
  );
}

export default App;

// tools/templates/frontend/angular/frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink],
  template: `
    <div class="app">
      <nav>
        <a routerLink="/">Home</a>
<% if (modules.contact) { -%>
        <a routerLink="/contact">Contact</a>
<% } -%>
<% if (modules.auth) { -%>
        <a routerLink="/login">Login</a>
<% } -%>
<% if (modules.admin) { -%>
        <a routerLink="/dashboard">Dashboard</a>
<% } -%>
      </nav>
      <main>
        <router-outlet />
      </main>
    </div>
  `
})
export class AppComponent {
  title = '<%= appName %>';
}
