// tools/templates/frontend/angular/frontend/src/app/components/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  standalone: true,
  template: `
    <div>
      <h1>Welcome to <%= AppName %></h1>
      <p>This is a full-stack application built with:</p>
      <ul>
        <li>Frontend: <%= frontend %></li>
        <li>Backend: <%= backend %></li>
        <li>Database: <%= db %></li>
<% if (modules.auth) { -%>
        <li>Auth: <%= auth %></li>
<% } -%>
<% if (modules.payments) { -%>
        <li>Payments: <%= payments %></li>
<% } -%>
      </ul>
    </div>
  `
})
export class HomeComponent {}

// tools/templates/frontend/vue/frontend/src/views/Home.vue
<template>
  <div>
    <h1>Welcome to <%= AppName %></h1>
    <p>This is a full-stack application built with:</p>
    <ul>
      <li>Frontend: <%= frontend %></li>
      <li>Backend: <%= backend %></li>
      <li>Database: <%= db %></li>
<% if (modules.auth) { -%>
      <li>Auth: <%= auth %></li>
<% } -%>
<% if (modules.payments) { -%>
      <li>Payments: <%= payments %></li>
<% } -%>
    </ul>

    <ApiTest />
  </div>
</template>

<script>
import ApiTest from './ApiTest.vue';

export default {
  name: 'Home',
  components: {
    ApiTest
  }
}
</script>
